name: Test, Bump Package Version and Tag
on:
  pull_request:
    branches:
      - develop
    types: [closed]
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          token: ${{secrets.GH_TOKEN}}
      - uses: actions/checkout@v2
      - run:  |
          npm ci
          npm test
          npm version patch